### ISSUE TITLE
too many Ring, Charm, or Head slots

### ISSUE THREAD

**Issue by itzacookie** [TheIllusiveC4/Curios#177]
I add mods and they keep adding new slots to the baubles tab.  I have 8 ring slots and only want 4, as well as 8 charms and only want 3.  I cannot figure out how to change this.  How can i?

**Comment by TheIllusiveC4** [comment]
This would only occur if the mods are purposefully adding more slots. Which mods are causing this behavior?
As a last resort, you can override the behavior yourself by using the `curios-server.toml` file as outlined here:
https://github.com/TheIllusiveC4/Curios/wiki/How-to-Use:-Users

Something like:
```toml
[[curiosSettings]]
  identifier = "ring"
  size = 4
  override = true
```
